import { useCallback, useEffect, useState } from 'react';
import styled from 'styled-components';
import { PainelLayout } from '../components/PainelLayout';
import { useFuncionarioAuth } from '../context/FuncionarioAuthContext';
import { buscarPedidos, atualizarStatusPedido } from '../../pizzaria/api/pedido.service';
import type { Pedido, StatusPedido } from '../../../store/pedido.store';

const Cartao=styled.div`background:#fff;border-radius:16px;padding:1.5rem;box-shadow:0 4px 16px rgba(15,23,42,.06);margin-bottom:1rem;`;
const Botao=styled.button`border:0;border-radius:10px;padding:.65rem 1rem;cursor:pointer;font-weight:600;margin-right:.5rem;`;
export function BalcaoPage(){const{funcionario}=useFuncionarioAuth();const[pedidos,setPedidos]=useState<Pedido[]>([]);const[erro,setErro]=useState('');const carregar=useCallback(async()=>{try{setPedidos(await buscarPedidos());setErro('')}catch(e){setErro(e instanceof Error?e.message:'Falha ao carregar pedidos.')}},[]);useEffect(()=>{void carregar();const t=window.setInterval(()=>void carregar(),5000);return()=>window.clearInterval(t)},[carregar]);async function mudar(id:string,status:StatusPedido){try{await atualizarStatusPedido(id,status);await carregar()}catch(e){setErro(e instanceof Error?e.message:'Falha ao atualizar pedido.')}}return <PainelLayout icone="🧾" titulo="Painel do Balcão"><Cartao><h2>Olá, {funcionario?.nome}!</h2><p>Acompanhe em tempo real os pedidos recebidos pelo site e pelo atendimento.</p>{erro&&<p>{erro}</p>}</Cartao>{pedidos.map(p=><Cartao key={p.id}><b>#{p.id.slice(0,8).toUpperCase()}</b><p>{p.dados.cliente.nome} · {p.dados.cliente.telefone}</p><p>{p.itens.map(i=>`${i.quantidade}x ${i.nome}`).join(', ')}</p><p>Status: <b>{p.status}</b></p>{p.status==='recebido'&&<Botao onClick={()=>void mudar(p.id,'cancelado')}>Cancelar</Botao>}{p.status==='aguardando_envio'&&<Botao onClick={()=>void mudar(p.id,'saiu_para_entrega')}>Enviar</Botao>}</Cartao>)}{pedidos.length===0&&<Cartao><p>Nenhum pedido registrado.</p></Cartao>}</PainelLayout>}
